application: nothingtees
version: 0-2a
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /index\.html
  script: main.py

- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /.*
  script: main.py
